---
galaxy_info:
  author: Barry Britt <bbritt@iastate.edu>
  description: A simple role for installing and configuring an rsyslog forwarder.
  company: Iowa State University

  issue_tracker_url: https://github.com/ISU-Ansible/ansible-rsyslog/issues/

  license: GPLv2

  min_ansible_version: 2.0

  platforms:
    - name: EL
      versions:
      - 6
      - 7

  galaxy_tags:
    - rsyslog
    - system

